name: Docker

on:
    workflow_call:
 
jobs:

  Docker:
    runs-on: ubuntu_latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup docker builda
      uses: docker/setup-buildx-action@v2.0.0
      